# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Miss Curie
email: chloej4hack@gmail.com
description: t@lking to the MOON
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.misscurie.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  moontshing

# Build settings
markdown: kramdown
